version: '3.1'

services:
  mysql_server:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: agrotis
      MYSQL_ROOT_PASSWORD: agrotis
      MYSQL_TCP_PORT: 3307
    ports:
      - 3307:3307
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
