spring:
  config:
    activate:
      on-profile: test
  flyway:
    url: jdbc:h2:mem:agrotis
    schemas: agrotis
    user: root
    locations: classpath:db/migration
    validate-migration-naming: true
  datasource:
    url: jdbc:h2:mem:agrotis
    driver-class-name: org.h2.Driver
    username: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
